trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformWorkingDirectory: './Terraform'

stages:
- stage: 
  jobs:
  - job: 
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.13.1'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(terraformWorkingDirectory)'
        backendServiceArm: 'Azure 1'
        backendAzureRmStorageAccountName: 'satfstateeast'
        backendAzureRmContainerName: 'tfstate-audiobooks'
        backendAzureRmKey: 'audiobooks.tfstate'
        backendAzureRmResourceGroupName: 'rg-Terraform-Requirements'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(terraformWorkingDirectory)'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(terraformWorkingDirectory)'
        environmentServiceNameAzureRM: 'Azure 1'
        commandOptions: '-out=tfplan'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(terraformWorkingDirectory)'
        environmentServiceNameAzureRM: 'Azure 1'
        commandOptions: '-auto-approve tfplan'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure 1'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $appId = azuread_application.abs.client_id
          $fqdn = azurerm_container_group.aci.fqdn
          az ad app update --id $appId --web-redirect-uris "https://$fqdn/" "https://$fqdn/auth/openid/callback"