trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformWorkingDirectory: './Terraform'

stages:
- stage: 
  jobs:
  - job: 
    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.13.1'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(terraformWorkingDirectory)'
        backendServiceArm: 'Azure 1'
        backendAzureRmStorageAccountName: 'satfstateeast'
        backendAzureRmContainerName: 'tfstate-audiobooks'
        backendAzureRmKey: 'audiobooks.tfstate'
        backendAzureRmResourceGroupName: 'rg-Terraform-Requirements'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(terraformWorkingDirectory)'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(terraformWorkingDirectory)'
        environmentServiceNameAzureRM: 'Azure 1'
        commandOptions: '-out=tfplan'

    - task: TerraformTaskV4@4
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(terraformWorkingDirectory)'
        environmentServiceNameAzureRM: 'Azure 1'
        commandOptions: '-auto-approve tfplan'

    - script: |
        #!/bin/bash
        APP_ID=$(terraform output -raw abs_client_id)
        ACI_FQDN=$(terraform output -raw abs_redirect_uri | sed 's|https://||;s|/auth/openid/callback||')
        az ad app update --id "$APP_ID" \
          --web-redirect-uris "https://$ACI_FQDN/" "https://$ACI_FQDN/auth/openid/callback"
      displayName: 'Update Azure AD App Registration Redirect URIs'